menu:
  Home: /
  Archives: /archives

widgets:
- category
- tag
- archive
- about

excerpt_link: Read More

author-face: "http://www.gravatar.com/avatar/fbb492eea89d797c4a00f455a03ed5e8.jpg?s=512"

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true
scrollup: true

google_analytics:
rss:

comment_provider: 
# Facebook comment
facebook:
  appid: 
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
